#FROM andrius/alpine-ruby:latest
#FROM i386/ruby:2.6.6-alpine3.11
#FROM i386/ruby:2.6-alpine3.12
FROM i386/ruby:2.6.6-alpine3.12
ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN apk add --update ruby-dev build-base \
     && gem install bundler \
    && bundle install \
    && apk del ruby-dev build-base
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
