global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#irina_tokareva'
