---
- name: Start Docker container
  hosts: all
  become: true
  tasks:
  # deploy db & app reddit
  - name: run container 
    docker_container:
      name: reddit 
      image: itokareva/otus-reddit:1.0
      ports:
        - "9292:9292"
