version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT_H}:${PORT_C}/${PRO}
    networks:
      - front_net
  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COM_VER}
    environment: 
      - COMMENT_DATABASE_HOST=comment_db
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net: 
