---
#
- name: create catalog kuber config
  file:
    path: /etc/kubernetes/config
    state: directory
    mode: '0755'
- name: create catalog kuber config
  file:
    path: /var/lib/kubernetes
    state: directory
    mode: '0755'    
- name: download kube-apiserver
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-apiserver
    dest: /usr/local/bin
    mode: 0644
- name: download kube-controller-manager
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-controller-manager
    dest: /usr/local/bin
    mode: 0644
- name: download kube-scheduler
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-scheduler
    dest: /usr/local/bin
    mode: 0644
- name: download kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl
    dest: /usr/local/bin
    mode: 0644    
- name: Add unit file for kube-apiserver.service
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify: reload kube-apiserver
- name: Add unit file for kube-controller-manager.service
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
- name: Add unit file for kube-scheduler.service
  template: 
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
- name: Create config file kube-scheduler.yaml
  template:
    src: kube-scheduler.config.j2
    dest: /etc/kubernetes/config/kube-scheduler.yaml
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes        
- name: enable kube-apiserver.service
  systemd: 
    name: kube-apiserver.service
    enabled: yes
    state: started
- name: enable kube-controller-manager.service
  systemd: 
    name: kube-controller-manager.service
    enabled: yes
    state: started 
- name: enable kube-scheduler.service
  systemd: 
    name: kube-scheduler.service
    enabled: yes
    state: started        
    
