{
 "title": "ui_service_monitoring",
 "time": { "from": "2020-09-03T14:10:49.000Z", "to": "2020-09-03T14:15:09.000Z" },
 "panels": [
  {
   "title": "HTTP Response Time 95%",
   "type": "graph",
   "description": "95  percentile",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Rate of UI http requests with error",
   "type": "graph",
   "description": "Rate of UI http requests with error",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "All http requests that UI sercice receives",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[1m])" }
   ]
  }
 ]
}