groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: UIHighRequestLatency 
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))>0.05 
#      expr: ui_request_response_time_bucket{quantile="0.95"}>0.05 
      for: 1m
      labels:
        severity: page 
      annotations:
        description: "{{ $labels.instance }} has a 95 percentile request latency above 0.05s (current value: {{ $value }}s)"
        summary: "High request latency on {{ $labels.instance }}" 
        
