kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: RsnVv78qlv1iVdorNjRwJW13TcrOmMvxoCNHks+t3cY=
      - identity: {}
