version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT_H}:${PORT_C}/${PRO}
    networks:
      - front_net
  post:
    env_file: .env
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    build: ./comment
    image: ${USERNAME}/comment:${COM_VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net: 
